### ISSUE TITLE
AttributeError: module 'modules.chat' has no attribute 'save_persistent_history'

### ISSUE THREAD

**Issue by deng232** [SicariusSicariiStuff/Diffusion_TTS#4]
```
2023-10-12 00:46:00 INFO:Loading the extension "Diffusion_TTS"...
Traceback (most recent call last):
  File "C:\stuff\textg\text-generation-webui\server.py", line 237, in <module>
    create_interface()
  File "C:\stuff\textg\text-generation-webui\server.py", line 140, in create_interface
    extensions_module.create_extensions_block()  # Extensions block
  File "C:\stuff\textg\text-generation-webui\modules\extensions.py", line 192, in create_extensions_block
    extension.ui()
  File "C:\stuff\textg\text-generation-webui\extensions\Diffusion_TTS\script.py", line 393, in ui
    chat.save_persistent_history, gradio('history', 'character_menu', 'mode'), None).then(
AttributeError: module 'modules.chat' has no attribute 'save_persistent_history'
```
when restarting UI with only Diffusion_TSS
all requirements are installed 
windows 11 using with oobabooga

**Comment by christopherquenneville** [comment]
I believe this is why:
https://github.com/oobabooga/text-generation-webui/issues/4037

"This issue is now remedied with built in Silero. Other TTS extensions need updating."

**Comment by gtbloody** [comment]
replace "save_persistent_history“ by "save_history" in  script.py

**Comment by SicariusSicariiStuff** [comment]
Thank you for reporting and suggesting the fix. I implemented it, it now works.
Also, make sure that samples are set to at least 16 to avoid empty tensor errors.
