### ISSUE TITLE
Multiple errors in latest Oobabooga.

### ISSUE THREAD

**Issue by CRCODE22** [SicariusSicariiStuff/Diffusion_TTS#5]
`Traceback (most recent call last):

File "K:\text-generation-webui\extensions\Diffusion_TTS\script.py", line 289, in output_modifier

generate_audio(model, voice_samples, conditioning_latents, output_dir, output_file, gen_kwargs, texts)

File "K:\text-generation-webui\extensions\Diffusion_TTS\script.py", line 325, in generate_audio

gen = tts.tts_with_preset(text, voice_samples=samples, conditioning_latents=latents, **gen_kwargs)

File "K:\text-generation-webui\extensions\Diffusion_TTS\tortoise\tortoise\api.py", line 353, in tts_with_preset

return self.tts(text, **settings)

File "K:\text-generation-webui\extensions\Diffusion_TTS\tortoise\tortoise\api.py", line 416, in tts

auto_conditioning, diffusion_conditioning, auto_conds, _ = self.get_conditioning_latents(voice_samples, return_mels=True)

File "K:\text-generation-webui\extensions\Diffusion_TTS\tortoise\tortoise\api.py", line 308, in get_conditioning_latents

cond_mel = wav_to_univnet_mel(sample.to(self.device), do_normalization=False, device=self.device)

File "K:\text-generation-webui\installer_files\env\lib\site-packages\tortoise\utils\audio.py", line 184, in wav_to_univnet_mel

stft = TacotronSTFT(1024, 256, 1024, 100, 24000, 0, 12000)

File "K:\text-generation-webui\installer_files\env\lib\site-packages\tortoise\utils\audio.py", line 147, in init

self.stft_fn = STFT(filter_length, hop_length, win_length)

File "K:\text-generation-webui\installer_files\env\lib\site-packages\tortoise\utils\stft.py", line 120, in init

fft_window = torch.from_numpy(fft_window).float()

RuntimeError: Numpy is not available`

Numpy is installed so should be available.

**Comment by SicariusSicariiStuff** [comment]
windows is currently not officially supported, I updated the extension and it currently tested with the latest booga version and it works.
